### ISSUE TITLE
airspeed measurement gets stuck

### ISSUE THREAD

**Issue by wynn4** [byu-magicc/ROSflight#116]
I was just looking over the rosbag from the most recent flight and noticed that the airspeed measurement kept getting stuck.  It would update a bunch (as it should), get stuck for some length of time (varying), update a bunch, and so on...

Please see the 'flat spots' in the following plot:

![airspeed_velocity](https://cloud.githubusercontent.com/assets/21351818/24018810/1ebd87ee-0a5b-11e7-91cf-6300fa03354d.png)

**Comment by superjax** [comment]
I haven't been able to replicate this on the ground yet.  I'm wondering if it was a bad wiring connection.  (That would cause the same behavior.)  Perhaps I need to add a watchdog to the driver that reports zeros if the I2C fails to read.

**Comment by superjax** [comment]
We might also consider hot gluing a molex connector to the naze so we can avoid intermiitent connections.

**Comment by wynn4** [comment]
Sounds plausible.  Before the next test I'll wok with those guys to make sure we have a solid connection

**Comment by superjax** [comment]
I just pulled out the airspeed sensor I've been bench testing with, and it seems to be working great.

I'm still suspicious that it was a intermittent connection, because I just ran this sensor for about 20 minutes without it freezing up like that.  If it's not the connection, then perhaps the sensor itself needs to be replaced.

At the very least, I am unable to replicate it on the ground with my hardware.

![image](https://cloud.githubusercontent.com/assets/7344014/24228967/d1815f1e-0f3c-11e7-8390-8041350ccebe.png)
