### ISSUE TITLE
timeout error greater than 32 bit range

### ISSUE THREAD

**Issue by danems11** [byu-magicc/ROSflight#89]

**Comment by superjax** [comment]
This is a pretty serious bug.  The micros timer rolls over after 70 minutes.  The solution is to convert the micros() function to return a 64-bit integer, which would roll over in 73,000 years!

**Comment by superjax** [comment]
@danems11, I just pushed this fix to the latest polling branch.  Would you give it a try?  It turns out that the micros timer resets after 70 minutes.  Since you guys are using this for a long period of time, would you mind watching the time on the IMU message to make sure that it doesn't reset after about 70 minutes?

**Comment by danems11** [comment]
We will test it out. Thank you.

**Comment by superjax** [comment]
I'm going to close this for now.  I suspect that it is working with that previous commit
